/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package code;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Erlangga L. P
 */
public class DosenFrame extends javax.swing.JFrame {
    private Statement st ;
    private Connection con;
    private ResultSet rs;
    String ambil_id = "";
    String def_pass_dosen = PrivateData.get_pass_dosen();

    /**
     * Creates new form DosenFrame
     */
    public DosenFrame() {
        initComponents();
        sambungDB();
        Tampildata_dosenTIF();
    }
    
     //Sambung Database Lokal
     private void sambungDB() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver"); //Menentukan Driver untuk tersambung ke Database
            String url = PrivateData.get_urlDB(); //URL letak Database
            String pengguna = PrivateData.get_userDB(); //user untuk login Database
            String pass = PrivateData.get_passDB();
            
            con = DriverManager.getConnection(url, pengguna, pass); //Untuk menyambungkan Driver ke Database
            
        } catch (Exception e) {
            System.out.println("Database GAGAL Tersambung " + e.getMessage()); //Menampilkan pesan gagal
        }
    }
     
    private void Tampildata_dosenTIF() {
        try {
           st = con.createStatement();
           rs = st.executeQuery("SELECT * FROM `dosen` WHERE `dosen_prodi`='TIF_SDA';");
            
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("ID Dosen");
            model.addColumn("Nama Dosen");
            model.addColumn("Nomor Telepon");
            
            model.getDataVector().removeAllElements();
            model.fireTableDataChanged();
            model.setRowCount(0);
            
            while (rs.next()){
                Object [] data = {
                    rs.getString("id_dosen"),rs.getString("nama_dosen"),rs.getString("nomor_telp")};
                model.addRow(data);
                tabel_dosen.setModel(model);
           
            }
            combo_tampilData.setSelectedIndex(0);
            
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    }
    
    private void Tampildata_dosenMID() {
        try {
           st = con.createStatement();
           rs = st.executeQuery("SELECT * FROM `dosen` WHERE `dosen_prodi`='MID_SDA';");
            
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("ID Dosen");
            model.addColumn("Nama Dosen");
            model.addColumn("Nomor Telepon");
            
            model.getDataVector().removeAllElements();
            model.fireTableDataChanged();
            model.setRowCount(0);
            
            while (rs.next()){
                Object [] data = {
                    rs.getString("id_dosen"),rs.getString("nama_dosen"),rs.getString("nomor_telp")};
                model.addRow(data);
                tabel_dosen.setModel(model);
           
            }
            combo_tampilData.setSelectedIndex(1);
            
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_dosen = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        combo_tampilData = new javax.swing.JComboBox<>();
        btn_tampilData = new javax.swing.JButton();
        btn_tambah = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_ubah = new javax.swing.JButton();
        btn_batal = new javax.swing.JButton();
        txt_nama = new javax.swing.JTextField();
        txt_idDosen = new javax.swing.JTextField();
        txt_alamat = new javax.swing.JTextField();
        txt_telpon = new javax.swing.JTextField();
        combo_prodi = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        btn_resetPassword = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        tabel_dosen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Dosen", "Nama Dosen", "Alamat", "Nomor Telepon"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabel_dosen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_dosenMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_dosen);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 377, 960, 310));

        combo_tampilData.setBackground(new java.awt.Color(0, 0, 153));
        combo_tampilData.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        combo_tampilData.setForeground(new java.awt.Color(255, 255, 255));
        combo_tampilData.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TIF SIDOARJO", "MID SIDOARJO" }));
        combo_tampilData.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        combo_tampilData.setNextFocusableComponent(btn_tampilData);
        getContentPane().add(combo_tampilData, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 290, 150, 30));

        btn_tampilData.setBackground(new java.awt.Color(255, 255, 0));
        btn_tampilData.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_tampilData.setText("TAMPILKAN");
        btn_tampilData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tampilDataActionPerformed(evt);
            }
        });
        getContentPane().add(btn_tampilData, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 330, 150, 30));

        btn_tambah.setBackground(new java.awt.Color(0, 102, 0));
        btn_tambah.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_tambah.setForeground(new java.awt.Color(255, 255, 255));
        btn_tambah.setText("TAMBAH");
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });
        getContentPane().add(btn_tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, 110, 30));

        btn_delete.setBackground(new java.awt.Color(0, 102, 0));
        btn_delete.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_delete.setForeground(new java.awt.Color(255, 255, 255));
        btn_delete.setText("HAPUS");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        getContentPane().add(btn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 100, 30));

        btn_ubah.setBackground(new java.awt.Color(0, 102, 0));
        btn_ubah.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_ubah.setForeground(new java.awt.Color(255, 255, 255));
        btn_ubah.setText("PERBARUI");
        btn_ubah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubahActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, 120, 30));

        btn_batal.setBackground(new java.awt.Color(0, 102, 0));
        btn_batal.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_batal.setForeground(new java.awt.Color(255, 255, 255));
        btn_batal.setText("BATAL");
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });
        getContentPane().add(btn_batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 330, 100, 30));

        txt_nama.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(txt_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 200, 30));

        txt_idDosen.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(txt_idDosen, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 200, 30));

        txt_alamat.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(txt_alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, 200, 30));

        txt_telpon.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(txt_telpon, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, 200, 30));

        combo_prodi.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        combo_prodi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TIF SIDOARJO", "MID SIDOARJO" }));
        getContentPane().add(combo_prodi, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 200, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Nama");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 60, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("ID Dosen");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, -1, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Alamat");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, -1, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Nomor Telepon");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, -1, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Program Studi");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, -1, 30));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icon-home.png"))); // NOI18N
        back.setText("jLabel2");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 6, 60, 60));

        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icon-minimize.png"))); // NOI18N
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        getContentPane().add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, -10, 30, 30));

        btn_resetPassword.setBackground(new java.awt.Color(255, 0, 0));
        btn_resetPassword.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_resetPassword.setForeground(new java.awt.Color(255, 255, 255));
        btn_resetPassword.setText("RESET PASSWORD");
        btn_resetPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(btn_resetPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 130, 200, 30));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Dosen_Desain.jpg"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        // TODO add your handling code here:
        try {
            st = con.createStatement();
            if(txt_nama.getText().equals("") || txt_idDosen.getText().equals("") || txt_alamat.getText().equals("") || txt_telpon.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Seluruh kolom harus di terpenuhi!");
            }else{
                String sql = "SELECT * FROM `dosen` WHERE `id_dosen`='"+txt_idDosen.getText()+"';";
                java.sql.Connection con = (Connection)PrivateData.sambungDB();
                java.sql.PreparedStatement ps = con.prepareStatement(sql);
                java.sql.ResultSet r = ps.executeQuery(sql);
                if(r.next()){
                    JOptionPane.showMessageDialog(this, "Data Sudah Ada!");
                }else{
                    String prodi_sql;
                    String pilihan_prodi = combo_prodi.getSelectedItem().toString();
                    if(pilihan_prodi.equalsIgnoreCase("TIF SIDOARJO")){
                        prodi_sql ="TIF_SDA";
                        st.executeUpdate("INSERT INTO `dosen` "
                                + "(`dosen_prodi`, `nama_dosen`, `id_dosen`, `alamat`, `nomor_telp`, `pass_dosen`) "
                                + "VALUES ('"+ prodi_sql +"', '"+txt_nama.getText()+"', "
                                + "'"+txt_idDosen.getText()+"', '"+txt_alamat.getText()+"', "
                                + "'"+txt_telpon.getText()+"', MD5('"+def_pass_dosen+"'));");
                        JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
                        txt_nama.setText("");
                        txt_idDosen.setText("");
                        txt_alamat.setText("");
                        txt_telpon.setText("");
                        combo_prodi.setSelectedIndex(0);
                        Tampildata_dosenTIF();
                        
                    }else if(pilihan_prodi.equalsIgnoreCase("MID SIDOARJO")){
                        prodi_sql ="MID_SDA";
                        st.executeUpdate("INSERT INTO `dosen` "
                                + "(`dosen_prodi`, `nama_dosen`, `id_dosen`, `alamat`, `nomor_telp`, `pass_dosen`) "
                                + "VALUES ('"+ prodi_sql +"', '"+txt_nama.getText()+"', "
                                + "'"+txt_idDosen.getText()+"', '"+txt_alamat.getText()+"', "
                                + "'"+txt_telpon.getText()+"', MD5('"+def_pass_dosen+"'));");
                        JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
                        txt_nama.setText("");
                        txt_idDosen.setText("");
                        txt_alamat.setText("");
                        txt_telpon.setText("");
                        combo_prodi.setSelectedIndex(0);
                        Tampildata_dosenMID();
                        
                    }else{
                        JOptionPane.showMessageDialog(null, "Prodi Tidak Ditemukan");
                    }
                }
            }
        } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
            if ( ambil_id.equals("")){
                JOptionPane.showMessageDialog(this, "Silahkan Pilih Data Yang Akan Dihapus");
            }else{
                String[] opsi = {"YA" , "TIDAK"};
                int jawab = JOptionPane.showOptionDialog(null, 
                        "Apakah Anda Yakin Akan \nMenghapus Data Ini?", 
                        "Konfirmasi" ,
                        JOptionPane.YES_NO_OPTION, 
                        JOptionPane.QUESTION_MESSAGE, null, opsi, opsi[1]);
                if ( jawab == JOptionPane.YES_OPTION ) {
                    try {
                        st =con.createStatement();
                        st.executeUpdate("DELETE FROM `dosen` WHERE `id_dosen`='"+ambil_id+"';");
                        JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                        st.close();
                        txt_nama.setText("");
                        txt_idDosen.setText("");
                        txt_alamat.setText("");
                        txt_telpon.setText("");
                        combo_prodi.setSelectedIndex(0);
                        ambil_id = "";
                        Tampildata_dosenTIF();

                    }catch ( SQLException e){
                        JOptionPane.showMessageDialog(null, e);

                    }   
                }
            }
        
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahActionPerformed
        // TODO add your handling code here:
            String prodi_sql;
            String pilihan_prodi = combo_prodi.getSelectedItem().toString();
                if ( ambil_id.equals("")){
                    JOptionPane.showMessageDialog(this, "Silahkan Pilih Data Yang Akan Diperbarui");
                }else{
                    try {
                    st = con.createStatement();
                    if(pilihan_prodi.equalsIgnoreCase("TIF SIDOARJO")){
                        prodi_sql ="TIF_SDA";
                        st.executeUpdate("UPDATE `dosen` SET "
                                + "`dosen_prodi` = '"+prodi_sql+"', "
                                + "`nama_dosen` = '"+txt_nama.getText()+"', "
                                + "`alamat` = '"+txt_alamat.getText()+"', "
                                + "`nomor_telp` = '"+txt_telpon.getText()+"' "
                                + "WHERE `dosen`.`id_dosen` = '"+ambil_id+"';");
                        JOptionPane.showMessageDialog(null, "Data Berhasil Diperbarui");
                        txt_nama.setText("");
                        txt_idDosen.setText("");
                        txt_alamat.setText("");
                        txt_telpon.setText("");
                        combo_prodi.setSelectedIndex(0);
                        Tampildata_dosenTIF();
                        
                    }else if(pilihan_prodi.equalsIgnoreCase("MID SIDOARJO")){
                        prodi_sql ="MID_SDA";
                        st.executeUpdate("UPDATE `dosen` SET "
                                + "`dosen_prodi` = '"+prodi_sql+"', "
                                + "`nama_dosen` = '"+txt_nama.getText()+"', "
                                + "`alamat` = '"+txt_alamat.getText()+"', "
                                + "`nomor_telp` = '"+txt_telpon.getText()+"' "
                                + "WHERE `dosen`.`id_dosen` = '"+ambil_id+"';");
                        JOptionPane.showMessageDialog(null, "Data Berhasil Diperbarui");
                        txt_nama.setText("");
                        txt_idDosen.setText("");
                        txt_alamat.setText("");
                        txt_telpon.setText("");
                        combo_prodi.setSelectedIndex(0);
                        Tampildata_dosenMID();
                        
                    }else{
                        JOptionPane.showMessageDialog(null, "Data Tidak Ditemukan");
                    }
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, e);
                }
            }
    }//GEN-LAST:event_btn_ubahActionPerformed

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        // TODO add your handling code here:
        txt_nama.setText("");
        txt_idDosen.setText("");
        txt_alamat.setText("");
        txt_telpon.setText("");
        combo_prodi.setSelectedIndex(0);
        ambil_id = "";
   
    }//GEN-LAST:event_btn_batalActionPerformed

    private void tabel_dosenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_dosenMouseClicked
        // TODO add your handling code here:
        ambil_id = tabel_dosen.getValueAt(tabel_dosen.getSelectedRow(), 0).toString();
            try{
                st = con.createStatement();
                rs = st.executeQuery("SELECT * FROM `dosen` WHERE `id_dosen`='"+ambil_id+"';");
                if(rs.next()){
                    txt_idDosen.setEditable(false);
                    txt_nama.setText(rs.getString("nama_dosen"));
                    txt_idDosen.setText(rs.getString("id_dosen"));
                    txt_alamat.setText(rs.getString("alamat"));
                    txt_telpon.setText(rs.getString("nomor_telp"));
                    
                    String prodi_dosen = rs.getString("dosen_prodi");
                    if(prodi_dosen.equalsIgnoreCase("TIF_SDA")){
                        combo_prodi.setSelectedItem("TIF SIDOARJO");
                    }else if(prodi_dosen.equalsIgnoreCase("MID_SDA")){
                        combo_prodi.setSelectedItem("MID SIDOARJO");
                    }
                }
            }catch(SQLException e){
                JOptionPane.showMessageDialog(this, e);
            }
        
    }//GEN-LAST:event_tabel_dosenMouseClicked

    private void btn_tampilDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tampilDataActionPerformed
        // TODO add your handling code here:
        String tampilData = combo_tampilData.getSelectedItem().toString();
        if(tampilData.equalsIgnoreCase("TIF SIDOARJO")){
            Tampildata_dosenTIF();
        }else if(tampilData.equalsIgnoreCase("MID SIDOARJO")){
            Tampildata_dosenMID();
        }else{
            JOptionPane.showMessageDialog(null, "Data Tidak Ditemukan");
        }
    }//GEN-LAST:event_btn_tampilDataActionPerformed

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new DashboardFrame().setVisible(true);
    }//GEN-LAST:event_backMouseClicked

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void btn_resetPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetPasswordActionPerformed
        // TODO add your handling code here:
        String pilihan_prodi = combo_prodi.getSelectedItem().toString();
                if ( ambil_id.equals("")){
                    JOptionPane.showMessageDialog(this, "Silahkan Pilih Akun Dosen Yang Akan Direset Password");
                }else{
                    String[] opsi = {"YA" , "TIDAK"};
                    int jawab = JOptionPane.showOptionDialog(this, 
                            "Apakah anda yakin akan Reset Password?" , 
                            "Reset Password Dosen", 
                            JOptionPane.YES_NO_OPTION,
                            JOptionPane.QUESTION_MESSAGE, null, opsi, opsi[1]);

                    if (jawab == JOptionPane.YES_OPTION){
                        try {
                            st = con.createStatement();
                            if(pilihan_prodi.equalsIgnoreCase("TIF SIDOARJO")){
                                st.executeUpdate("UPDATE `dosen` SET `pass_dosen` = MD5('"+def_pass_dosen+"') WHERE `dosen`.`id_dosen` = '"+ambil_id+"';");
                                JOptionPane.showMessageDialog(null, "Password Akun Berhasil Direset");
                                txt_nama.setText("");
                                txt_idDosen.setText("");
                                txt_alamat.setText("");
                                txt_telpon.setText("");
                                combo_prodi.setSelectedIndex(0);
                                Tampildata_dosenTIF();

                            }else if(pilihan_prodi.equalsIgnoreCase("MID SIDOARJO")){
                                st.executeUpdate("UPDATE `dosen` SET `pass_dosen` = MD5('"+def_pass_dosen+"') WHERE `dosen`.`id_dosen` = '"+ambil_id+"';");
                                JOptionPane.showMessageDialog(null, "Password Akun Berhasil Direset");
                                txt_nama.setText("");
                                txt_idDosen.setText("");
                                txt_alamat.setText("");
                                txt_telpon.setText("");
                                combo_prodi.setSelectedIndex(0);
                                Tampildata_dosenMID();

                            }else{
                                JOptionPane.showMessageDialog(null, "Data Tidak Ditemukan");
                            }
                        } catch (SQLException e) {
                            JOptionPane.showMessageDialog(null, e);
                        }
                    }
                }
        
    }//GEN-LAST:event_btn_resetPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DosenFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DosenFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DosenFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DosenFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DosenFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JLabel bg;
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_resetPassword;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JButton btn_tampilData;
    private javax.swing.JButton btn_ubah;
    private javax.swing.JComboBox<String> combo_prodi;
    private javax.swing.JComboBox<String> combo_tampilData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel minimize;
    private javax.swing.JTable tabel_dosen;
    private javax.swing.JTextField txt_alamat;
    private javax.swing.JTextField txt_idDosen;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_telpon;
    // End of variables declaration//GEN-END:variables
}
