/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package code;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author maulidatul
 */
public class PengabdianFrame extends javax.swing.JFrame {
Connection con; 
 public Statement st;
 public ResultSet rs;
 public PreparedStatement ps;
 String ambil_id = "";
 String jenisAkun = PrivateData.get_jenisAkun();
    /**
     * Creates new form pengadian_masyarakattttttt
     */
    public PengabdianFrame() {
        initComponents();
        sambungDB ();
        TampilData();
        
    }
    
    String formatTGL = "yyyy-MM-dd";
    SimpleDateFormat fm = new SimpleDateFormat(formatTGL);
    String tanggal_pertemuan;
    
    public static java.util.Date getTanggal(JTable table, int kolom){
        JTable tabel = table;
        String str_tgl = String.valueOf(tabel.getValueAt(tabel.getSelectedRow(), kolom));
        java.util.Date tgl = null;
        try{
            tgl = new SimpleDateFormat("yyyy-MM-dd").parse(str_tgl);
        }catch(Exception e){
            System.out.println("Error GetTanggal "+e);
        }
        return tgl;
    }

    //Sambung Database Lokal
     private void sambungDB() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver"); //Menentukan Driver untuk tersambung ke Database
            String url = PrivateData.get_urlDB(); //URL letak Database
            String pengguna = PrivateData.get_userDB(); //user untuk login Database
            String pass = PrivateData.get_passDB();
            
            con = DriverManager.getConnection(url, pengguna, pass); //Untuk menyambungkan Driver ke Database
            
        } catch (Exception e) {
            System.out.println("Database GAGAL Tersambung " + e.getMessage()); //Menampilkan pesan gagal
        }
    }
     
@SuppressWarnings("empty-statement")
private void TampilData() {
        try {
            
            st = con.createStatement();
            rs = st.executeQuery("SELECT * FROM `pengabdian_masyarakat`");
            
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("ID Pengabdian");
            model.addColumn("Kegiatan");
            model.addColumn("Lokasi");
            model.addColumn("Tanggal");
            
            
            model.getDataVector().removeAllElements();
            model.fireTableDataChanged();
            model.setRowCount(0);
            
            while (rs.next()) {
                Object [] data = {
                   rs.getString("id_pengabdian"),rs.getString("kegiatan"),rs.getString("lokasi"),rs.getString("tanggal")};
                model.addRow(data);
                tabel_pengabdian.setModel(model);
                        }  
            
            
        } catch (Exception e) {
        }

}    
    
    private void kosong(){
        txt_idPengabdian.setText("");
        txt_Kegiatan.setText("");
        txt_lokasi.setText("");
        date_tgl.setDate(null);
        txt_idPengabdian.setEditable(true);
        ambil_id = "";
        tanggal_pertemuan = "";
    }

     /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_pengabdian = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        txt_idPengabdian = new javax.swing.JTextField();
        txt_Kegiatan = new javax.swing.JTextField();
        txt_lokasi = new javax.swing.JTextField();
        btn_tambah = new javax.swing.JButton();
        btn_ubah = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_batal = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        date_tgl = new com.toedter.calendar.JDateChooser();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabel_pengabdian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Pengabdian", "Kegiatan", "Lokasi", "Tanggal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabel_pengabdian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_pengabdianMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_pengabdian);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 377, 960, 310));

        txt_idPengabdian.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPanel1.add(txt_idPengabdian, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 110, 230, 30));

        txt_Kegiatan.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPanel1.add(txt_Kegiatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 160, 230, 30));

        txt_lokasi.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPanel1.add(txt_lokasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 210, 230, 30));

        btn_tambah.setBackground(new java.awt.Color(255, 255, 0));
        btn_tambah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_tambah.setText("TAMBAH");
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });
        jPanel1.add(btn_tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 320, 90, 25));

        btn_ubah.setBackground(new java.awt.Color(255, 255, 0));
        btn_ubah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_ubah.setText("PERBARUI");
        btn_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubahActionPerformed(evt);
            }
        });
        jPanel1.add(btn_ubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 320, 95, 25));

        btn_hapus.setBackground(new java.awt.Color(255, 255, 0));
        btn_hapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_hapus.setText("HAPUS");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });
        jPanel1.add(btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 320, 80, 25));

        btn_batal.setBackground(new java.awt.Color(255, 255, 0));
        btn_batal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_batal.setText("BATAL");
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });
        jPanel1.add(btn_batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 320, 80, 25));

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        jLabel1.setText("ID ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 112, 100, 30));

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        jLabel2.setText("Kegiatan");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 162, 100, 30));

        jLabel3.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        jLabel3.setText("Lokasi");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, 90, 30));

        jLabel4.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        jLabel4.setText("Tanggal");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, 80, 30));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icon-home.png"))); // NOI18N
        back.setText("jLabel2");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 6, 60, 60));

        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icon-minimize.png"))); // NOI18N
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        jPanel1.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, -10, 30, 30));

        date_tgl.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPanel1.add(date_tgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 260, 230, 30));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Pengabdian_Desain.png"))); // NOI18N
        jPanel1.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        try {
            tanggal_pertemuan = String.valueOf(fm.format(date_tgl.getDate()));
            st = con.createStatement();
            if(txt_idPengabdian.getText().equals("") || txt_Kegiatan.getText().equals("") || txt_lokasi.getText().equals("") || date_tgl.getDate()==null){
                JOptionPane.showMessageDialog(this, "Seluruh kolom harus di terpenuhi!");
            }else{
                String sql1 = "SELECT * FROM `pengabdian_masyarakat` WHERE `id_pengabdian`='"+txt_idPengabdian.getText()+"';";
                java.sql.Connection con = (Connection)PrivateData.sambungDB();
                java.sql.PreparedStatement ps = con.prepareStatement(sql1);
                java.sql.ResultSet r = ps.executeQuery(sql1);
                if(r.next()){
                    JOptionPane.showMessageDialog(this, "Data Sudah Ada!");
                }else{
                    st.executeUpdate("INSERT INTO `pengabdian_masyarakat` "
                            + "(`id_pengabdian`, `kegiatan`, `lokasi`, `tanggal`) VALUES "
                            + "('"+txt_idPengabdian.getText()+"', "
                            + "'"+txt_Kegiatan.getText()+"', "
                            + "'"+txt_lokasi.getText()+"', "
                            + "'"+tanggal_pertemuan+"');");
                    JOptionPane.showMessageDialog(this, "Data Berhasil Disimpan");
                    kosong();
                    TampilData();
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void btn_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahActionPerformed
    try{
        tanggal_pertemuan = String.valueOf(fm.format(date_tgl.getDate()));
        st = con.createStatement();
                if(ambil_id.equals("")){
                    JOptionPane.showMessageDialog(this, "Silahkan Pilih Data Yang Akan Diperbarui");
                }else{
                    st.executeUpdate("UPDATE `pengabdian_masyarakat` SET "
                        + "`id_pengabdian` = '"+txt_idPengabdian.getText()+"', "
                        + "`kegiatan` = '"+txt_Kegiatan.getText()+"', "
                        + "`lokasi` = '"+txt_lokasi.getText()+"', "
                        + "`tanggal` = '"+tanggal_pertemuan+"' "
                        + "WHERE `pengabdian_masyarakat`.`id_pengabdian` = '"+ambil_id+"';");

                    JOptionPane.showMessageDialog(null, " Data Berhasil Diperbarui");
                    kosong();
                    TampilData();
                }
        
    }catch(SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btn_ubahActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
       try{
            st = con.createStatement();
                    if(ambil_id.equals("")){
                        JOptionPane.showMessageDialog(this, "Silahkan Pilih Data Yang Akan Dihapus");
                    }else{
                        String[] opsi = {"YA" , "TIDAK"};
                        int jawab = JOptionPane.showOptionDialog(null, 
                                "Apakah Anda Yakin Akan \nMenghapus Data Ini?", 
                                "Konfirmasi" ,
                                JOptionPane.YES_NO_OPTION, 
                                JOptionPane.QUESTION_MESSAGE, null, opsi, opsi[1]);
                        if ( jawab == JOptionPane.YES_OPTION ) {
                                st.executeUpdate("DELETE FROM `pengabdian_masyarakat` WHERE `id_pengabdian`='"+ambil_id+"';");
                                JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                                kosong();
                                TampilData();
                        }
                    }
        }catch(SQLException e) {
                JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        // TODO add your handling code here:
        if(jenisAkun.equalsIgnoreCase("Administrator")){
            this.setVisible(false);
            new DashboardFrame().setVisible(true);
        }else if(jenisAkun.equalsIgnoreCase("Dosen")){
            this.setVisible(false);
            new DashboardFrame_Dosen().setVisible(true);
        }
    }//GEN-LAST:event_backMouseClicked

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void tabel_pengabdianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_pengabdianMouseClicked
        // TODO add your handling code here:
        txt_idPengabdian.setText(tabel_pengabdian.getValueAt(tabel_pengabdian.getSelectedRow(), 0).toString());
        txt_Kegiatan.setText(tabel_pengabdian.getValueAt(tabel_pengabdian.getSelectedRow(), 1).toString());
        txt_lokasi.setText(tabel_pengabdian.getValueAt(tabel_pengabdian.getSelectedRow(), 2).toString());
        date_tgl.setDate(getTanggal(tabel_pengabdian, 3));
        ambil_id = tabel_pengabdian.getValueAt(tabel_pengabdian.getSelectedRow(), 0).toString();
        txt_idPengabdian.setEditable(false);
    }//GEN-LAST:event_tabel_pengabdianMouseClicked

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        // TODO add your handling code here:
        kosong();
    }//GEN-LAST:event_btn_batalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PengabdianFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PengabdianFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PengabdianFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PengabdianFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PengabdianFrame().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JLabel bg;
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JButton btn_ubah;
    private com.toedter.calendar.JDateChooser date_tgl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel minimize;
    private javax.swing.JTable tabel_pengabdian;
    private javax.swing.JTextField txt_Kegiatan;
    private javax.swing.JTextField txt_idPengabdian;
    private javax.swing.JTextField txt_lokasi;
    // End of variables declaration//GEN-END:variables
}
