/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package code;

import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author Erlangga L. P
 */
public class ProfileFrame extends javax.swing.JFrame {
    String ambil_id, ambil_id2 = "", akun, jenisAkun_login, sql = "";
    String jenisAkun = PrivateData.get_jenisAkun();

    /**
     * Creates new form ProfileFrame
     */
    public ProfileFrame() {
        initComponents();
        TampilData_akun();
    }
    
    private void TampilData_akun(){
        try {
            Connection conn = (Connection)PrivateData.sambungDB();
            ambil_id = PrivateData.get_user_id();
            akun = PrivateData.get_jenisAkun();
            jenisAkun_login = PrivateData.get_akunLogin();
            if(ambil_id.equals("") || akun.equals("")){
                JOptionPane.showMessageDialog(this, "ID Tidak Ditemukan");
            }else{
                if(akun.equalsIgnoreCase("Administrator")){
                    sql = "SELECT * FROM `admin` WHERE `id_admin`='"+ambil_id+"';";
                    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                    java.sql.ResultSet rs = pst.executeQuery(sql);
                    if(rs.next()){
                        label_id.setText("Nomor Identitas Administrator");
                        txt_id.setText(rs.getString("id_admin"));
                        txt_nama.setText(rs.getString("nama_admin"));
                        txt_alamat.setText(rs.getString("alamat_admin"));
                        txt_telpon.setText(rs.getString("telp_admin"));
                    }
                }else if(akun.equalsIgnoreCase("Dosen")){
                    sql = "SELECT * FROM `dosen` WHERE `id_dosen`='"+ambil_id+"';";
                    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                    java.sql.ResultSet rs = pst.executeQuery(sql);
                    if(rs.next()){
                        label_id.setText("Nomor Induk Dosen(NIDN)");
                        txt_id.setText(rs.getString("id_dosen"));
                        txt_nama.setText(rs.getString("nama_dosen"));
                        txt_alamat.setText(rs.getString("alamat"));
                        txt_telpon.setText(rs.getString("nomor_telp"));
                    }
                }else if(akun.equalsIgnoreCase("Mahasiswa")){
//                    if(jenisAkun_login.equalsIgnoreCase("Mahasiswa TIF")){
                        sql = "SELECT * FROM `mahasiswa` WHERE `nim`='"+ambil_id+"';";
                        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                        java.sql.ResultSet rs = pst.executeQuery(sql);
                        if(rs.next()){
                            label_id.setText("Nomor Induk Mahasiswa(NIM)");
                            txt_id.setText(rs.getString("nim"));
                            txt_nama.setText(rs.getString("nama_mahasiswa"));
                            txt_alamat.setText(rs.getString("alamat"));
                            txt_telpon.setText(rs.getString("nomor_telp"));
                        }
//                    }else if(jenisAkun_login.equalsIgnoreCase("Mahasiswa MID")){
//                        sql = "SELECT * FROM `mahasiswa_mid` WHERE `nim`='"+ambil_id+"';";
//                        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
//                        java.sql.ResultSet rs = pst.executeQuery(sql);
//                        if(rs.next()){
//                            label_id.setText("Nomor Induk Mahasiswa(NIM)");
//                            txt_id.setText(rs.getString("nim"));
//                            txt_nama.setText(rs.getString("nama_mahasiswa"));
//                            txt_alamat.setText(rs.getString("alamat"));
//                            txt_telpon.setText(rs.getString("nomor_telp"));
//                        }
//                    }
                    
                }
                
            }
            
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label_id = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        label_nama = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();
        label_alamat = new javax.swing.JLabel();
        txt_alamat = new javax.swing.JTextField();
        label_telpon = new javax.swing.JLabel();
        txt_telpon = new javax.swing.JTextField();
        back = new javax.swing.JLabel();
        panel_update_password = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pass_baru = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        pass_lama = new javax.swing.JPasswordField();
        check_tampilsandi = new javax.swing.JCheckBox();
        btn_batalGantiPassword = new javax.swing.JButton();
        btn_perbaruiPassword = new javax.swing.JButton();
        minimize = new javax.swing.JLabel();
        btn_perbaruiAkun = new javax.swing.JButton();
        btn_editAkun = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_id.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label_id.setText("Nomor Induk Mahasiswa(NIM)");
        jPanel1.add(label_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, 30));

        txt_id.setEditable(false);
        txt_id.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jPanel1.add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 300, 35));

        label_nama.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label_nama.setText("Nama Lengkap");
        jPanel1.add(label_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, 30));

        txt_nama.setEditable(false);
        txt_nama.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jPanel1.add(txt_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 300, 35));

        label_alamat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label_alamat.setText("Alamat");
        jPanel1.add(label_alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, 30));

        txt_alamat.setEditable(false);
        txt_alamat.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jPanel1.add(txt_alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 300, 35));

        label_telpon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label_telpon.setText("Nomor Telepon");
        jPanel1.add(label_telpon, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, -1, 30));

        txt_telpon.setEditable(false);
        txt_telpon.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jPanel1.add(txt_telpon, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 300, 35));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icon-home.png"))); // NOI18N
        back.setText("jLabel2");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 630, 60, 60));

        panel_update_password.setBackground(new java.awt.Color(0, 0, 153));
        panel_update_password.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PERBARUI PASSWORD ANDA");
        panel_update_password.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 480, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PASSWORD BARU");
        panel_update_password.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 460, 30));

        pass_baru.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        pass_baru.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        panel_update_password.add(pass_baru, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 460, 35));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PASSWORD LAMA");
        panel_update_password.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 80, 460, 30));

        pass_lama.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        pass_lama.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        panel_update_password.add(pass_lama, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 460, 35));

        check_tampilsandi.setBackground(new java.awt.Color(0, 0, 153));
        check_tampilsandi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        check_tampilsandi.setForeground(new java.awt.Color(255, 255, 255));
        check_tampilsandi.setText("Tampilkan Password");
        check_tampilsandi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_tampilsandiActionPerformed(evt);
            }
        });
        panel_update_password.add(check_tampilsandi, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 140, -1));

        btn_batalGantiPassword.setBackground(new java.awt.Color(204, 0, 0));
        btn_batalGantiPassword.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_batalGantiPassword.setForeground(new java.awt.Color(255, 255, 255));
        btn_batalGantiPassword.setText("BATALKAN");
        btn_batalGantiPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalGantiPasswordActionPerformed(evt);
            }
        });
        panel_update_password.add(btn_batalGantiPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 210, 35));

        btn_perbaruiPassword.setBackground(new java.awt.Color(255, 255, 0));
        btn_perbaruiPassword.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_perbaruiPassword.setText("SIMPAN PASSWORD");
        btn_perbaruiPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_perbaruiPasswordActionPerformed(evt);
            }
        });
        panel_update_password.add(btn_perbaruiPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 210, 35));

        jPanel1.add(panel_update_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 520, 340));

        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icon-minimize.png"))); // NOI18N
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        jPanel1.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, -10, 30, 30));

        btn_perbaruiAkun.setBackground(new java.awt.Color(0, 0, 51));
        btn_perbaruiAkun.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_perbaruiAkun.setForeground(new java.awt.Color(255, 255, 255));
        btn_perbaruiAkun.setText("PERBARUI");
        btn_perbaruiAkun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_perbaruiAkunActionPerformed(evt);
            }
        });
        jPanel1.add(btn_perbaruiAkun, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 520, 140, 35));

        btn_editAkun.setBackground(new java.awt.Color(51, 0, 0));
        btn_editAkun.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_editAkun.setForeground(new java.awt.Color(255, 255, 255));
        btn_editAkun.setText("EDIT AKUN");
        btn_editAkun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editAkunActionPerformed(evt);
            }
        });
        jPanel1.add(btn_editAkun, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, 140, 35));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Profile_Desain.png"))); // NOI18N
        jPanel1.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 700));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        // TODO add your handling code here:
        if(jenisAkun.equalsIgnoreCase("Administrator")){
            this.setVisible(false);
            new DashboardFrame().setVisible(true);
        }else if(jenisAkun.equalsIgnoreCase("Dosen")){
            this.setVisible(false);
            new DashboardFrame_Dosen().setVisible(true);
        }
    }//GEN-LAST:event_backMouseClicked

    private void check_tampilsandiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_tampilsandiActionPerformed
        // TODO add your handling code here:
        if(check_tampilsandi.isSelected()){
            pass_lama.setEchoChar((char)0);
            pass_baru.setEchoChar((char)0);
        } else {
            pass_lama.setEchoChar('•');
            pass_baru.setEchoChar('•');
        }
    }//GEN-LAST:event_check_tampilsandiActionPerformed

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void btn_batalGantiPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalGantiPasswordActionPerformed
        // TODO add your handling code here:
        pass_lama.setText("");
        pass_baru.setText("");
    }//GEN-LAST:event_btn_batalGantiPasswordActionPerformed

    private void btn_editAkunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editAkunActionPerformed
        // TODO add your handling code here:
        txt_nama.setEditable(true);
        txt_alamat.setEditable(true);
        txt_telpon.setEditable(true);
        ambil_id2 = ambil_id;
    }//GEN-LAST:event_btn_editAkunActionPerformed

    private void btn_perbaruiAkunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_perbaruiAkunActionPerformed
        // TODO add your handling code here:
        try {
            Connection conn = (Connection)PrivateData.sambungDB();
            ambil_id = PrivateData.get_user_id();
            akun = PrivateData.get_jenisAkun();
            jenisAkun_login = PrivateData.get_akunLogin();
            if(ambil_id2.equals("")){
                JOptionPane.showMessageDialog(this, 
                                "AKSES DITOLAK!!! \nSilahkan Klik EDIT AKUN Terlebih Dahulu" , 
                                "Perbarui Akun" , 
                                JOptionPane.WARNING_MESSAGE);
            }else{
                if(akun.equalsIgnoreCase("Administrator")){
                    sql = "UPDATE `admin` SET "
                                + "`nama_admin` = '"+txt_nama.getText()+"', "
                                + "`alamat_admin` = '"+txt_alamat.getText()+"', "
                                + "`telp_admin` = '"+txt_telpon.getText()+"' "
                                + "WHERE `admin`.`id_admin` = '"+ambil_id2+"';";
                        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                        pst.executeUpdate(sql);
                        JOptionPane.showMessageDialog(null, 
                                "Akun Berhasil Diperbarui", 
                                "Perbarui Akun", 
                                JOptionPane.INFORMATION_MESSAGE);
                        ambil_id2 = "";
                        txt_nama.setEditable(false);
                        txt_alamat.setEditable(false);
                        txt_telpon.setEditable(false);
                        TampilData_akun();
                }else if(akun.equalsIgnoreCase("Dosen")){
                    sql = "UPDATE `dosen` SET "
                                + "`nama_dosen` = '"+txt_nama.getText()+"', "
                                + "`alamat` = '"+txt_alamat.getText()+"', "
                                + "`nomor_telp` = '"+txt_telpon.getText()+"' "
                                + "WHERE `dosen`.`id_dosen` = '"+ambil_id2+"';";
                        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                        pst.executeUpdate(sql);
                        JOptionPane.showMessageDialog(null, 
                                "Akun Berhasil Diperbarui", 
                                "Perbarui Akun", 
                                JOptionPane.INFORMATION_MESSAGE);
                        ambil_id2 = "";
                        txt_nama.setEditable(false);
                        txt_alamat.setEditable(false);
                        txt_telpon.setEditable(false);
                        TampilData_akun();
                }else if(akun.equalsIgnoreCase("Mahasiswa")){
                    if(jenisAkun_login.equalsIgnoreCase("Mahasiswa TIF")){
                        sql = "UPDATE `mahasiswa` SET "
                                + "`nama_mahasiswa` = '"+txt_nama.getText()+"', "
                                + "`alamat` = '"+txt_alamat.getText()+"', "
                                + "`nomor_telp` = '"+txt_telpon.getText()+"' "
                                + "WHERE `mahasiswa`.`nim` = '"+ambil_id2+"';";
                        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                        pst.executeUpdate(sql);
                        JOptionPane.showMessageDialog(null, 
                                "Akun Berhasil Diperbarui", 
                                "Perbarui Akun", 
                                JOptionPane.INFORMATION_MESSAGE);
                        ambil_id2 = "";
                        txt_nama.setEditable(false);
                        txt_alamat.setEditable(false);
                        txt_telpon.setEditable(false);
                        TampilData_akun();
                    }else if(jenisAkun_login.equalsIgnoreCase("Mahasiswa MID")){
                        sql = "UPDATE `mahasiswa_mid` SET "
                                + "`nama_mahasiswa` = '"+txt_nama.getText()+"', "
                                + "`alamat` = '"+txt_alamat.getText()+"', "
                                + "`nomor_telp` = '"+txt_telpon.getText()+"' "
                                + "WHERE `mahasiswa_mid`.`nim` = '"+ambil_id2+"';";
                        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                        pst.executeUpdate(sql);
                        JOptionPane.showMessageDialog(null, 
                                "Akun Berhasil Diperbarui", 
                                "Perbarui Akun", 
                                JOptionPane.INFORMATION_MESSAGE);
                        ambil_id2 = "";
                        txt_nama.setEditable(false);
                        txt_alamat.setEditable(false);
                        txt_telpon.setEditable(false);
                        TampilData_akun();
                    }     
                }
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_btn_perbaruiAkunActionPerformed

    private void btn_perbaruiPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_perbaruiPasswordActionPerformed
        // TODO add your handling code here:
        try{
            Connection conn = (Connection)PrivateData.sambungDB();
            ambil_id = PrivateData.get_user_id();
            akun = PrivateData.get_jenisAkun();
            jenisAkun_login = PrivateData.get_akunLogin();
            if(ambil_id.equals("")){
                JOptionPane.showMessageDialog(this, "ID Tidak DItemukan");
            }else{
                if(pass_lama.getText().equals("") || pass_baru.getText().equals("")){
                    JOptionPane.showMessageDialog(this, "Seluruh kolom harus di terpenuhi!");
                }else{
                    if(akun.equalsIgnoreCase("Administrator")){
                        sql = "SELECT * FROM `admin` WHERE "
                            + "id_admin='"+ambil_id+"' "
                            + "and pass_admin=MD5('"+pass_lama.getText()+"')";
                            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                            java.sql.ResultSet rs = pst.executeQuery(sql);
                            if(rs.next()){
                                pst.executeUpdate("UPDATE `admin` SET `pass_admin` = MD5('"+pass_baru.getText()+"') WHERE `admin`.`id_admin` = '"+ambil_id+"';");
                                JOptionPane.showMessageDialog(null, "Password Akun Berhasil Diperbarui");
                                pass_lama.setText("");
                                pass_baru.setText("");
                            }else{
                                JOptionPane.showMessageDialog(this, 
                                    "AKSES DITOLAK!!! \nPassword Lama Anda Salah" , 
                                    "Perbarui Password" , 
                                    JOptionPane.WARNING_MESSAGE);
                                pass_lama.setText("");
                            }
                    }else if(akun.equalsIgnoreCase("Dosen")){
                        sql = "SELECT * FROM `dosen` WHERE "
                            + "id_dosen='"+ambil_id+"' "
                            + "and pass_dosen=MD5('"+pass_lama.getText()+"')";
                            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                            java.sql.ResultSet rs = pst.executeQuery(sql);
                            if(rs.next()){
                                pst.executeUpdate("UPDATE `dosen` SET `pass_dosen` = MD5('"+pass_baru.getText()+"') WHERE `dosen`.`id_dosen` = '"+ambil_id+"';");
                                JOptionPane.showMessageDialog(null, "Password Akun Berhasil Diperbarui");
                                pass_lama.setText("");
                                pass_baru.setText("");
                            }else{
                                JOptionPane.showMessageDialog(this, 
                                    "AKSES DITOLAK!!! \nPassword Lama Anda Salah" , 
                                    "Perbarui Password" , 
                                    JOptionPane.WARNING_MESSAGE);
                                pass_lama.setText("");
                            }
                    }else{
                        JOptionPane.showMessageDialog(this, 
                                    "AKSES DITOLAK!!! \nPassword Anda Tidak Dapat Diperbarui" , 
                                    "Perbarui Password" , 
                                    JOptionPane.WARNING_MESSAGE);
                        pass_lama.setText("");
                        pass_baru.setText("");
                    }
                }
                
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_btn_perbaruiPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProfileFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JLabel bg;
    private javax.swing.JButton btn_batalGantiPassword;
    private javax.swing.JButton btn_editAkun;
    private javax.swing.JButton btn_perbaruiAkun;
    private javax.swing.JButton btn_perbaruiPassword;
    private javax.swing.JCheckBox check_tampilsandi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_alamat;
    private javax.swing.JLabel label_id;
    private javax.swing.JLabel label_nama;
    private javax.swing.JLabel label_telpon;
    private javax.swing.JLabel minimize;
    private javax.swing.JPanel panel_update_password;
    private javax.swing.JPasswordField pass_baru;
    private javax.swing.JPasswordField pass_lama;
    private javax.swing.JTextField txt_alamat;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_telpon;
    // End of variables declaration//GEN-END:variables
}
